### ISSUE TITLE
Silly question, but how does one use this within nodejs?

### ISSUE THREAD

**Issue by henry74** [leapmotion/leapjs-plugins#18]
```
var plugins = require('leapjs-plugins')
.
.
.
  var controller = new Leap.Controller(leapConfig);
  controller.use(plugins.handEntry)
  controller.on('handLost',
    function(hand) {
      console.log('hand lost', hand);
    }
  )
```
Blows up with:
```
Error: Cannot find module './hand-entry/leap.hand-entry.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/henry74/test/node_modules/leapjs-plugins/index.js:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
Program node index.js exited with code 8
```

**Comment by AVGP** [comment]
I've hit that problem when I attempted using it with browserify.
I'll make a pull request with a patch soon :)
